apiVersion: v1
kind: ServiceAccount
metadata:
  name: public-api
  namespace: frontend
  annotations:
    iam.gke.io/gcp-service-account: pubapi-gsa@project-b3ca7570-d2b6-41c3-aaa.iam.gserviceaccount.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cv-processor
  namespace: backend
  annotations:
    iam.gke.io/gcp-service-account: cvproc-gsa@project-b3ca7570-d2b6-41c3-aaa.iam.gserviceaccount.com
